### General

# Set the width of the window (Deault: 640)
window_width: 640
# Set the height of the window (also used for things like detecting "existence" [on-screen position] of sprites) (Default: 480)
window_height: 480
# Set the starting score counter (Default: 0)
# When this equals the number of enemies, the game has been won.
# This can be used as a "Hanicap" because of this. (e.g. When a game has 20 enemies and you start with a score of 15, you only need to kill 5 enemies to win.)
score: 0


### Speed / Difficulty

# Overall gameplay speed (Default: 5 || Higher = slower / Lower = faster || 0 is minimum)
game_speed: 5
# Enemy ship speed (Default: 3)
enemy_speed: 3
# Number of enemies per row (Default: 10)
enemies_per_row: 10
# Number of enemy rows (Default: 2)
enemy_row_quantity: 2
# How large the enemy missiles should be (Default: 1 || Higher = bigger / Lower = smaller || 0.1 is minimum || Suggested minimum: 0.4)
enemy_missile_size: 1
# Enemy missile speed (Default: 5 - same as settings['player_missile_speed'])
enemy_missile_speed: 5
# How many missiles each row of enemies has to fire (Default: 1)
enemy_missiles_per_row: 2
# How far apart (vertically) the enemy rows are from each other (Default: 35 | Measured in pixels)
enemy_vertical_spacing: 35
# How far the enemy drops down when they reach the end of their row and drop down a line (Default: 7)
enemy_reverse_direction_drop_height: 7
# Player ship speed (Default: 5)
player_speed: 5
# How large the player's missile should be (Default: 1 || Higher = bigger / Lower = smaller || 0.1 is minimum || Suggested minimum: 0.4)
player_missile_size: 1
# Player missile speed (Default: 5)
player_missile_speed: 5
#NOT CURRENTLY WORKING
# Player missile fire speed (how "rapidly" the player can shoot) (Default: 2 | Measured in seconds)
player_missile_fire_speed: 2


### Cheats

# If this is '1', then pressing SPACE while a missile is on the screen will "override"/remove that missile from play and instantly create another
missile_override_option: 0
# If this is '1', then missiles will travel THROUGH enemies, rather than disappearing on collision
piercing_missiles: 1